# Generated by Django 4.2.9 on 2026-03-08 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SareePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loom_type', models.CharField(choices=[('2by1', '2 by 1'), ('4by1', '4 by 1')], max_length=10)),
                ('saree_length', models.CharField(choices=[('6m', '6 Meter'), ('9m', '9 Meter')], max_length=5)),
                ('saree_type', models.CharField(choices=[('self_saree', 'Self Saree'), ('kadiyal', 'Kadiyal'), ('gothila', 'Gothila')], max_length=20)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee_wage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('loom_type', 'saree_length', 'saree_type')},
            },
        ),
        migrations.CreateModel(
            name='ProductionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('loom_number', models.CharField(max_length=20)),
                ('loom_type', models.CharField(choices=[('2by1', '2 by 1'), ('4by1', '4 by 1')], max_length=10)),
                ('saree_length', models.CharField(choices=[('6m', '6 Meter'), ('9m', '9 Meter')], max_length=5)),
                ('saree_type', models.CharField(choices=[('self_saree', 'Self Saree'), ('kadiyal', 'Kadiyal'), ('gothila', 'Gothila')], max_length=20)),
                ('design_type', models.CharField(choices=[('butha', 'Butha'), ('mysore_silk', 'Mysore Silk'), ('checks', 'Checks'), ('stripes', 'Stripes'), ('floral', 'Floral'), ('border_work', 'Border Work'), ('zari_work', 'Zari Work'), ('other', 'Other')], default='butha', max_length=30)),
                ('quantity', models.PositiveIntegerField()),
                ('defects', models.PositiveIntegerField(default=0)),
                ('work_hours', models.DecimalField(decimal_places=1, default=8.0, max_digits=4)),
                ('wage_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saree_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saree_expense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saree_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to='employee.employee')),
            ],
            options={
                'db_table': 'production',
                'ordering': ['-date', 'employee__employee_id'],
            },
        ),
    ]
