# Generated by Django 4.2.9 on 2026-03-08 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0002_alter_productionentry_design_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
