# Generated by Django 4.2.9 on 2026-03-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('skill_level', models.CharField(choices=[('trainee', 'Trainee'), ('junior', 'Junior'), ('senior', 'Senior'), ('master', 'Master')], default='junior', max_length=20)),
                ('loom_number', models.CharField(max_length=20)),
                ('loom_type', models.CharField(choices=[('2by1', '2 by 1'), ('4by1', '4 by 1')], default='2by1', max_length=10)),
                ('joining_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['employee_id'],
            },
        ),
    ]
